fix: bash script to use right bracket

diff --git a/.github/workflows/dk_bus_sou.yml b/.github/workflows/dk_bus_sou.yml
--- a/.github/workflows/dk_bus_sou.yml
+++ b/.github/workflows/dk_bus_sou.yml
@@ -50,12 +50,12 @@ jobs:
             -DUSERNAME=$U_N \
             -DPASSWORD=$P_W \
             -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
-          IF EXIST slot-checker\target\value.txt (
-              echo File exists
-          ) ELSE (
-              echo Exiting with error: NO SLOTS AVAILABLE. 
-              exit /b 1
-          )
+          if [ -f slot-checker/target/value.txt ]; then
+            echo "File exists"
+          else
+            echo "Exiting with error: NO SLOTS AVAILABLE."
+            exit 1
+          fi
         env:
           PLAYWRIGHT_BROWSER_ARGS: --no-sandbox
           APP_URL: ${{secrets.DK_APP_URL}}
diff --git a/.github/workflows/wip_fileExist.yml b/.github/workflows/wip_fileExist.yml
--- a/.github/workflows/wip_fileExist.yml
+++ b/.github/workflows/wip_fileExist.yml
@@ -38,12 +38,12 @@ jobs:
           cd bot
           cd slot-checker
           mvn -B clean test -Dtest="JunitExploreTest" 
-          IF EXIST slot-checker\target\value.txt (
-              echo File exists
-          ) ELSE (
-              echo Exiting with error: NO SLOTS AVAILABLE. 
-              exit /b 1
-          )
+          if [ -f slot-checker/target/value.txt ]; then
+            echo "File exists"
+          else
+            echo "Exiting with error: NO SLOTS AVAILABLE."
+            exit 1
+          fi
         env:
           PLAYWRIGHT_BROWSER_ARGS: --no-sandbox
           APP_URL: ${{secrets.NL_APP_URL}}
